In [1]:
# Libraries

import requests

import pandas as pd

import numpy as np

import math

from datetime import datetime

from bs4 import BeautifulSoup

In [2]:
#============================================== CLASSICS =============================================

# Browser camouflage for website request
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'}

# Website URL for all ClassicS Books
url_classic = 'https://books.toscrape.com/catalogue/category/books/classics_6/index.html'

# Request
page = requests.get( url_classic, headers=headers )
page

# Returning the page's HTML
page.text

# Instantiating Beautiful Soup object
soup = BeautifulSoup(page.text, 'html.parser')
soup

# HTML structure (Class) where the showcase is stored (vitrine)
products = soup.find('ol', class_ = 'row')
products

#  HTML Structure (Class) where data is stored (all)
product_list = products.find_all('li', class_= 'col-xs-6 col-sm-4 col-md-3 col-lg-3')
product_list

# Returning first element of product_list
product_list[0]

# Number of items in the product_list
len(product_list)

product_list[0].get_text

#  HTML Structure (Class) where data is stored (details)
product_list_details = products.find_all('li', class_= 'col-xs-6 col-sm-4 col-md-3 col-lg-3')
product_list_details

#============================== Name ==============================
#============================== Price =============================
#============================== Stock =============================
#============================== Botton ============================

# Details
product_list_details[0].get_text()

#List de all products withe details (Name, Price, Stock, Botton)
product_all = [list(filter(None, p.get_text().split('\n'))) for p in product_list_details]
product_all

# Create DataFrame 
df = pd.DataFrame(product_all)

# Rename colomns DataFrame
df.columns = ['product_name','product_price','none','product_stock','none1','botton']

# Delete colmun
df.drop(["none", "none1"], axis=1, inplace=True)

#============================== Classification (STARS) ==============================

product_list_classification = products.find_all('p', class_= 'star-rating')
product_list_classification

# Counting the products on the page
len(product_list_classification)

# Extracting the number of stars per book
product_star = [product.p['class'] for product in product_list_details]
product_star = [p[1] for p in product_star] 

# Create DataFrame
df_star = pd.DataFrame(product_star)

# Rename column
df_star.columns = ['star']

#============================================== DATA =============================================

# Create DataFrame Finaly
data_classic = pd.concat([df, df_star], axis=1, ignore_index=True)

data_classic['product_catalog'] = 'Classic'
data_classic

# Rename de columns
data_classic.columns = ['product_name','product_price','product_stock','product_boton', 'product_star', 'product_catalog']

data_classic

,product_name,product_price,product_stock,product_boton,product_star,product_catalog
0,The Secret Garden,Â£15.08,In stock,Add to basket,Four,Classic
1,The Metamorphosis,Â£28.58,In stock,Add to basket,One,Classic
2,The Pilgrim's Progress,Â£50.26,In stock,Add to basket,Two,Classic
3,The Hound of the ...,Â£14.82,In stock,Add to basket,Two,Classic
4,Little Women (Little Women ...,Â£28.07,In stock,Add to basket,Four,Classic
5,Gone with the Wind,Â£32.49,In stock,Add to basket,Three,Classic
6,Candide,Â£58.63,In stock,Add to basket,Three,Classic
7,Animal Farm,Â£57.22,In stock,Add to basket,Three,Classic
8,Wuthering Heights,Â£17.73,In stock,Add to basket,Three,Classic
9,The Picture of Dorian ...,Â£29.70,In stock,Add to basket,Two,Classic
10,The Complete Stories and ...,Â£26.78,In stock,Add to basket,Four,Classic
11,Beowulf,Â£38.35,In stock,Add to basket,Two,Classic
12,And Then There Were ...,Â£35.01,In stock,Add to basket,Two,Classic
13,The Story of Hong ...,Â£43.19,In stock,Add to basket,Four,Classic
14,The Little Prince,Â£45.42,In stock,Add to basket,Two,Classic
15,Sense and Sensibility,Â£37.46,In stock,Add to basket,One,Classic
16,Of Mice and Men,Â£47.11,In stock,Add to basket,Two,Classic
17,Emma,Â£32.93,In stock,Add to basket,Two,Classic
18,Alice in Wonderland (Alice's ...,Â£55.53,In stock,Add to basket,One,Classic

In [3]:
#============================================== SCIENCE FICTION =============================================

# Browser camouflage for website request
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'}

# Website URL for all ClassicS Books
url_science = 'https://books.toscrape.com/catalogue/category/books/science-fiction_16/index.html'

# Request
page = requests.get( url_science, headers=headers )
page

# Returning the page's HTML
page.text

# Instantiating Beautiful Soup object
soup = BeautifulSoup(page.text, 'html.parser')
soup

# HTML structure (Class) where the showcase is stored (vitrine)
products = soup.find('ol', class_ = 'row')
products

#  HTML Structure (Class) where data is stored (all)
product_list = products.find_all('li', class_= 'col-xs-6 col-sm-4 col-md-3 col-lg-3')
product_list

# Returning first element of product_list
product_list[0]

# Number of items in the product_list
len(product_list)

product_list[0].get_text

#  HTML Structure (Class) where data is stored (details)
product_list_details = products.find_all('li', class_= 'col-xs-6 col-sm-4 col-md-3 col-lg-3')
product_list_details

#============================== Name ==============================
#============================== Price =============================
#============================== Stock =============================
#============================== Botton ============================

# Details
product_list_details[0].get_text()

#List de all products withe details (Name, Price, Stock, Botton)
product_all = [list(filter(None, p.get_text().split('\n'))) for p in product_list_details]
product_all

# Create DataFrame 
df = pd.DataFrame(product_all)

# Rename colomns DataFrame
df.columns = ['product_name','product_price','none','product_stock','none1','botton']

# Delete colmun
df.drop(["none", "none1"], axis=1, inplace=True)

#============================== Classification (STARS) ==============================

product_list_classification = products.find_all('p', class_= 'star-rating')
product_list_classification

# Counting the products on the page
len(product_list_classification)

# Extracting the number of stars per book
product_star = [product.p['class'] for product in product_list_details]
product_star = [p[1] for p in product_star] 

# Create DataFrame
df_star = pd.DataFrame(product_star)

# Rename column
df_star.columns = ['star']

#============================================== DATA =============================================

# Create DataFrame Finaly
data_science = pd.concat([df, df_star], axis=1, ignore_index=True)
data_science

data_science['product_catalog'] = 'Science Fiction '
data_science

# Rename de columns
data_science.columns = ['product_name','product_price','product_stock','product_boton', 'product_star', 'product_catalog']

data_science

,product_name,product_price,product_stock,product_boton,product_star,product_catalog
0,Mesaerion: The Best Science ...,Â£37.59,In stock,Add to basket,One,Science Fiction
1,Join,Â£35.67,In stock,Add to basket,Five,Science Fiction
2,William Shakespeare's Star Wars: ...,Â£43.30,In stock,Add to basket,Four,Science Fiction
3,The Project,Â£10.65,In stock,Add to basket,One,Science Fiction
4,Soft Apocalypse,Â£26.12,In stock,Add to basket,Two,Science Fiction
5,Sleeping Giants (Themis Files ...,Â£48.74,In stock,Add to basket,One,Science Fiction
6,Arena,Â£21.36,In stock,Add to basket,Four,Science Fiction
7,Foundation (Foundation (Publication Order) ...,Â£32.42,In stock,Add to basket,One,Science Fiction
8,The Restaurant at the ...,Â£10.92,In stock,Add to basket,One,Science Fiction
9,Ready Player One,Â£19.07,In stock,Add to basket,Four,Science Fiction
10,"Life, the Universe and ...",Â£33.26,In stock,Add to basket,Two,Science Fiction
11,Dune (Dune #1),Â£54.86,In stock,Add to basket,One,Science Fiction
12,Do Androids Dream of ...,Â£51.48,In stock,Add to basket,One,Science Fiction
13,Three Wishes (River of ...,Â£44.18,In stock,Add to basket,Two,Science Fiction
14,The Last Girl (The ...,Â£36.26,In stock,Add to basket,Two,Science Fiction
15,Having the Barbarian's Baby ...,Â£34.96,In stock,Add to basket,Four,Science Fiction

In [4]:
#============================================== HUMOR =============================================

# Browser camouflage for website request
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'}

# Website URL for all ClassicS Books
url_humor = 'https://books.toscrape.com/catalogue/category/books/humor_30/index.html'

# Request
page = requests.get( url_humor, headers=headers )
page

# Returning the page's HTML
page.text

# Instantiating Beautiful Soup object
soup = BeautifulSoup(page.text, 'html.parser')
soup

# HTML structure (Class) where the showcase is stored (vitrine)
products = soup.find('ol', class_ = 'row')
products

#  HTML Structure (Class) where data is stored (all)
product_list = products.find_all('li', class_= 'col-xs-6 col-sm-4 col-md-3 col-lg-3')
product_list

# Returning first element of product_list
product_list[0]

# Number of items in the product_list
len(product_list)

product_list[0].get_text

#  HTML Structure (Class) where data is stored (details)
product_list_details = products.find_all('li', class_= 'col-xs-6 col-sm-4 col-md-3 col-lg-3')
product_list_details

#============================== Name ==============================
#============================== Price =============================
#============================== Stock =============================
#============================== Botton ============================

# Details
product_list_details[0].get_text()

#List de all products withe details (Name, Price, Stock, Botton)
product_all = [list(filter(None, p.get_text().split('\n'))) for p in product_list_details]
product_all

# Create DataFrame 
df = pd.DataFrame(product_all)

# Rename colomns DataFrame
df.columns = ['product_name','product_price','none','product_stock','none1','botton']

# Delete colmun
df.drop(["none", "none1"], axis=1, inplace=True)

#============================== Classification (STARS) ==============================

product_list_classification = products.find_all('p', class_= 'star-rating')
product_list_classification

# Counting the products on the page
len(product_list_classification)

# Extracting the number of stars per book
product_star = [product.p['class'] for product in product_list_details]
product_star = [p[1] for p in product_star] 

# Create DataFrame
df_star = pd.DataFrame(product_star)

# Rename column
df_star.columns = ['star']

#============================================== DATA =============================================

# Create DataFrame Finaly
data_humor = pd.concat([df, df_star], axis=1, ignore_index=True)
data_humor

data_humor['product_catalog'] = ' Humor '
data_humor

# Rename de columns
data_humor.columns = ['product_name','product_price','product_stock','product_boton', 'product_star', 'product_catalog']

data_humor

,product_name,product_price,product_stock,product_boton,product_star,product_catalog
0,The Long Haul (Diary ...,Â£44.07,In stock,Add to basket,One,Humor
1,Old School (Diary of ...,Â£11.83,In stock,Add to basket,Five,Humor
2,I Know What I'm ...,Â£25.98,In stock,Add to basket,Four,Humor
3,Hyperbole and a Half: ...,Â£14.75,In stock,Add to basket,Five,Humor
4,Dress Your Family in ...,Â£43.68,In stock,Add to basket,Three,Humor
5,Toddlers Are A**holes: It's ...,Â£25.55,In stock,Add to basket,One,Humor
6,When You Are Engulfed ...,Â£30.89,In stock,Add to basket,Five,Humor
7,Naked,Â£31.69,In stock,Add to basket,Three,Humor
8,Lamb: The Gospel According ...,Â£55.50,In stock,Add to basket,Five,Humor
9,Holidays on Ice,Â£51.07,In stock,Add to basket,Two,Humor

In [5]:
#============================================== BUSINESS =============================================

# Browser camouflage for website request
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'}

# Website URL for all ClassicS Books
url_business = 'https://books.toscrape.com/catalogue/category/books/business_35/index.html'

# Request
page = requests.get( url_business, headers=headers )
page

# Returning the page's HTML
page.text

# Instantiating Beautiful Soup object
soup = BeautifulSoup(page.text, 'html.parser')
soup

# HTML structure (Class) where the showcase is stored (vitrine)
products = soup.find('ol', class_ = 'row')
products

#  HTML Structure (Class) where data is stored (all)
product_list = products.find_all('li', class_= 'col-xs-6 col-sm-4 col-md-3 col-lg-3')
product_list

# Returning first element of product_list
product_list[0]

# Number of items in the product_list
len(product_list)

product_list[0].get_text

#  HTML Structure (Class) where data is stored (details)
product_list_details = products.find_all('li', class_= 'col-xs-6 col-sm-4 col-md-3 col-lg-3')
product_list_details

#============================== Name ==============================
#============================== Price =============================
#============================== Stock =============================
#============================== Botton ============================

# Details
product_list_details[0].get_text()

#List de all products withe details (Name, Price, Stock, Botton)
product_all = [list(filter(None, p.get_text().split('\n'))) for p in product_list_details]
product_all

# Create DataFrame 
df = pd.DataFrame(product_all)

# Rename colomns DataFrame
df.columns = ['product_name','product_price','none','product_stock','none1','botton']

# Delete colmun
df.drop(["none", "none1"], axis=1, inplace=True)

#============================== Classification (STARS) ==============================

product_list_classification = products.find_all('p', class_= 'star-rating')
product_list_classification

# Counting the products on the page
len(product_list_classification)

# Extracting the number of stars per book
product_star = [product.p['class'] for product in product_list_details]
product_star = [p[1] for p in product_star] 

# Create DataFrame
df_star = pd.DataFrame(product_star)

# Rename column
df_star.columns = ['star']

#============================================== DATA =============================================

# Create DataFrame Finaly
data_business = pd.concat([df, df_star], axis=1, ignore_index=True)
data_business

data_business['product_catalog'] = ' Business '
data_business

# Rename de columns
data_business.columns = ['product_name','product_price','product_stock','product_boton', 'product_star', 'product_catalog']

data_business

,product_name,product_price,product_stock,product_boton,product_star,product_catalog
0,The Dirty Little Secrets ...,Â£33.34,In stock,Add to basket,Four,Business
1,The Third Wave: An ...,Â£12.61,In stock,Add to basket,Five,Business
2,The 10% Entrepreneur: Live ...,Â£27.55,In stock,Add to basket,Three,Business
3,Shoe Dog: A Memoir ...,Â£23.99,In stock,Add to basket,Two,Business
4,Made to Stick: Why ...,Â£38.85,In stock,Add to basket,Five,Business
5,Quench Your Own Thirst: ...,Â£43.14,In stock,Add to basket,One,Business
6,The Art of Startup ...,Â£21.00,In stock,Add to basket,Three,Business
7,Born for This: How ...,Â£21.59,In stock,Add to basket,Five,Business
8,The E-Myth Revisited: Why ...,Â£36.91,In stock,Add to basket,One,Business
9,"Rich Dad, Poor Dad",Â£51.74,In stock,Add to basket,One,Business
10,The Lean Startup: How ...,Â£33.92,In stock,Add to basket,Three,Business
11,Rework,Â£44.88,In stock,Add to basket,Two,Business

In [6]:
data_row = pd.concat([data_classic, data_science, data_humor, data_business],ignore_index=True)

# Delete colmun
data_row.drop(['product_boton'], axis=1, inplace=True)

data_row

,product_name,product_price,product_stock,product_star,product_catalog
0,The Secret Garden,Â£15.08,In stock,Four,Classic
1,The Metamorphosis,Â£28.58,In stock,One,Classic
2,The Pilgrim's Progress,Â£50.26,In stock,Two,Classic
3,The Hound of the ...,Â£14.82,In stock,Two,Classic
4,Little Women (Little Women ...,Â£28.07,In stock,Four,Classic
5,Gone with the Wind,Â£32.49,In stock,Three,Classic
6,Candide,Â£58.63,In stock,Three,Classic
7,Animal Farm,Â£57.22,In stock,Three,Classic
8,Wuthering Heights,Â£17.73,In stock,Three,Classic
9,The Picture of Dorian ...,Â£29.70,In stock,Two,Classic
10,The Complete Stories and ...,Â£26.78,In stock,Four,Classic
11,Beowulf,Â£38.35,In stock,Two,Classic
12,And Then There Were ...,Â£35.01,In stock,Two,Classic
13,The Story of Hong ...,Â£43.19,In stock,Four,Classic
14,The Little Prince,Â£45.42,In stock,Two,Classic
15,Sense and Sensibility,Â£37.46,In stock,One,Classic
16,Of Mice and Men,Â£47.11,In stock,Two,Classic
17,Emma,Â£32.93,In stock,Two,Classic
18,Alice in Wonderland (Alice's ...,Â£55.53,In stock,One,Classic
19,Mesaerion: The Best Science ...,Â£37.59,In stock,One,Science Fiction
20,Join,Â£35.67,In stock,Five,Science Fiction
21,William Shakespeare's Star Wars: ...,Â£43.30,In stock,Four,Science Fiction
22,The Project,Â£10.65,In stock,One,Science Fiction
23,Soft Apocalypse,Â£26.12,In stock,Two,Science Fiction
24,Sleeping Giants (Themis Files ...,Â£48.74,In stock,One,Science Fiction
25,Arena,Â£21.36,In stock,Four,Science Fiction
26,Foundation (Foundation (Publication Order) ...,Â£32.42,In stock,One,Science Fiction
27,The Restaurant at the ...,Â£10.92,In stock,One,Science Fiction
28,Ready Player One,Â£19.07,In stock,Four,Science Fiction
29,"Life, the Universe and ...",Â£33.26,In stock,Two,Science Fiction
30,Dune (Dune #1),Â£54.86,In stock,One,Science Fiction
31,Do Androids Dream of ...,Â£51.48,In stock,One,Science Fiction
32,Three Wishes (River of ...,Â£44.18,In stock,Two,Science Fiction
33,The Last Girl (The ...,Â£36.26,In stock,Two,Science Fiction
34,Having the Barbarian's Baby ...,Â£34.96,In stock,Four,Science Fiction
35,The Long Haul (Diary ...,Â£44.07,In stock,One,Humor
36,Old School (Diary of ...,Â£11.83,In stock,Five,Humor
37,I Know What I'm ...,Â£25.98,In stock,Four,Humor
38,Hyperbole and a Half: ...,Â£14.75,In stock,Five,Humor
39,Dress Your Family in ...,Â£43.68,In stock,Three,Humor
40,Toddlers Are A**holes: It's ...,Â£25.55,In stock,One,Humor
41,When You Are Engulfed ...,Â£30.89,In stock,Five,Humor
42,Naked,Â£31.69,In stock,Three,Humor
43,Lamb: The Gospel According ...,Â£55.50,In stock,Five,Humor
44,Holidays on Ice,Â£51.07,In stock,Two,Humor
45,The Dirty Little Secrets ...,Â£33.34,In stock,Four,Business
46,The Third Wave: An ...,Â£12.61,In stock,Five,Business
47,The 10% Entrepreneur: Live ...,Â£27.55,In stock,Three,Business
48,Shoe Dog: A Memoir ...,Â£23.99,In stock,Two,Business
49,Made to Stick: Why ...,Â£38.85,In stock,Five,Business
50,Quench Your Own Thirst: ...,Â£43.14,In stock,One,Business
51,The Art of Startup ...,Â£21.00,In stock,Three,Business
52,Born for This: How ...,Â£21.59,In stock,Five,Business
53,The E-Myth Revisited: Why ...,Â£36.91,In stock,One,Business
54,"Rich Dad, Poor Dad",Â£51.74,In stock,One,Business
55,The Lean Startup: How ...,Â£33.92,In stock,Three,Business
56,Rework,Â£44.88,In stock,Two,Business

In [7]:
data_row.to_csv('data_row.csv')